[Log]
log_collector       = on
log_level           = log
log_destination     = file
log_filename        = /var/log/hgproxy/hgproxy.log
log_format          = "%d %-5V [pid:%p cid:%U %F:%L] %m%n"
log_rotation_size   = 500MB

[Proxy]
listen_addresses    = *
port                = 5866
socket_dir          = /tmp
process_nums        = 6
max_connection      = 1000
extension_module    = librwsplit.so
process_cpu_mode    = system
auto_replace_application_name = "hgproxy: app[__IP__:__PORT__:__ORIGINAL__]"
use_mctx = off

[BackendNode]
node_num            = 1
load_balancing_mode = 1
hostname0           = 127.0.0.1
port0               = 5867
backend_weigh0      = 1
read_timeout_close  = 300

[Replication]
streaming_replication_switch        = off
streaming_replication_delay_time    = 8000

[DatabaseCheck]
lifecheck_user      = sysdba
lifecheck_dbname    = highgo
lifecheck_time      = 30
lifecheck_num       = 3

[BlackList]
ignore_regex_case               = off
black_regex_token_list          =
white_regex_token_list          =
object_relationship_list        = /opt/highgo/hgproxy/etc/object_relationship_list.json

[SSL]
ssl_switch                = off
ssl_cert                  = /data/hg_test/server.crt
ssl_key                   = /data/hg_test/server.key
ssl_ca_cert               = /data/hg_test/root.crt
ssl_ciphers               = HIGH:MEDIUM:+3DES:!aNULL
ssl_prefer_server_ciphers = on
ssl_ecdh_curve            = prime256v1
ssl_dh_params_file        =

[RAFT]
raft_switch     = off
raft_hostname   = 127.0.0.1
raft_port       = 2379
raft_key        = \047/service\047
raft_server     = \047http://127.0.0.1:2379\047
